USE BBBS;

ALTER TABLE Customer ADD createdAt DATETIME NOT NULL;

ALTER TABLE Booking ADD createdAt DATETIME NOT NULL;
ALTER TABLE Booking ADD reservationTimeOut BOOLEAN NOT NULL;
ALTER TABLE Booking ADD canceled BOOLEAN NOT NULL;